const chartdata = [
  {
    name: "OneRPM",
    distribution_cost: { value: "$0", weighted_value: 0 },
    commission: 15,
    stores: 38,
    video_distribution: {
      value: true,
      hint: "Free (50% of commission)",
      weighted_value: 1,
    },
    content_id: true,
    ig_music: true,
    payout_minimum: 0,
    soundcloud_monetization: false,
    make_changes_after_distribution: {
      value: true,
      hint: "Artwork, Titles, Audio Files",
    },
    marketing_tools: {
      value: true,
      hint: "Smart Links, Pre-Save, Promo Art",
      weighted_value: 1,
    },
  },
  {
    name: "Amuse (Free Plan)",
    distribution_cost: { value: "$0", weighted_value: 0 },
    commission: 0,
    stores: 9,
    video_distribution: {
      value: false,
      hint: null,
      weighted_value: 0,
    },
    content_id: false,
    ig_music: false,
    payout_minimum: 10,
    soundcloud_monetization: false,
    make_changes_after_distribution: {
      value: true,
      hint: "Artwork",
    },
    marketing_tools: {
      value: true,
      hint: "Smart Links",
      weighted_value: 1,
    },
  },
  {
    name: "Amuse (Paid Plan)",
    distribution_cost: { value: "$60/yr", weighted_value: 2 },
    commission: 0,
    stores: 14,
    video_distribution: {
      value: false,
      hint: null,
      weighted_value: 0,
    },
    content_id: true,
    ig_music: true,
    payout_minimum: 10,
    soundcloud_monetization: false,
    make_changes_after_distribution: {
      value: true,
      hint: "Artwork",
    },
    marketing_tools: {
      value: true,
      hint: "Smart Links",
      weighted_value: 1,
    },
  },
  {
    name: "Novecore",
    distribution_cost: { value: "$0", weighted_value: 0 },
    commission: 15,
    stores: 27,
    video_distribution: {
      value: false,
      hint: null,
      weighted_value: 0,
    },
    content_id: true,
    ig_music: true,
    payout_minimum: 0,
    soundcloud_monetization: true,
    make_changes_after_distribution: {
      value: false,
      hint: null,
    },
    marketing_tools: {
      value: false,
      hint: null,
      weighted_value: 0,
    },
  },
  {
    name: "Soundrop",
    distribution_cost: { value: "$0", weighted_value: 0 },
    commission: 15,
    stores: 12,
    video_distribution: {
      value: false,
      hint: null,
      weighted_value: 0,
    },
    content_id: false,
    ig_music: true,
    payout_minimum: 20,
    soundcloud_monetization: false,
    make_changes_after_distribution: {
      value: true,
      hint: "Artwork, Titles",
    },
    marketing_tools: {
      value: true,
      hint: "Pre-Save, Show.co Tools",
      weighted_value: 1,
    },
  },
  {
    name: "United Masters",
    distribution_cost: { value: "$0", weighted_value: 0 },
    commission: 10,
    stores: 31,
    video_distribution: {
      value: true,
      hint: "Only If Accepted",
      weighted_value: 1,
    },
    content_id: true,
    ig_music: true,
    payout_minimum: 50,
    soundcloud_monetization: true,
    make_changes_after_distribution: {
      value: false,
      hint: null,
    },
    marketing_tools: {
      value: true,
      hint: "Smart Links, Pre-Save",
      weighted_value: 1,
    },
  },
  {
    name: "Routenote (Free Plan)",
    distribution_cost: { value: "$0", weighted_value: 0 },
    commission: 15,
    stores: 28,
    video_distribution: {
      value: false,
      hint: null,
      weighted_value: 0,
    },
    content_id: true,
    ig_music: true,
    payout_minimum: 50,
    soundcloud_monetization: true,
    make_changes_after_distribution: {
      value: true,
      hint: "Artwork, Titles",
    },
    marketing_tools: {
      value: false,
      hint: null,
      weighted_value: 0,
    },
  },
  {
    name: "DistroKid",
    distribution_cost: { value: "$19.99/yr", weighted_value: 1 },
    commission: 0,
    stores: 17,
    video_distribution: {
      value: false,
      hint: null,
      weighted_value: 0,
    },
    content_id: true,
    ig_music: true,
    payout_minimum: 0,
    soundcloud_monetization: true,
    make_changes_after_distribution: {
      value: true,
      hint: "Artwork, Titles",
    },
    marketing_tools: {
      value: true,
      hint: "Pre-save",
      weighted_value: 1,
    },
  },
  {
    name: "Freshtunes",
    distribution_cost: { value: "$0", weighted_value: 0 },
    commission: 0,
    stores: 15,
    video_distribution: {
      value: false,
      hint: null,
      weighted_value: 0,
    },
    content_id: true,
    ig_music: false,
    payout_minimum: 25,
    soundcloud_monetization: false,
    make_changes_after_distribution: {
      value: false,
      hint: null,
    },
    marketing_tools: {
      value: true,
      hint: "Promotion",
      weighted_value: 1,
    },
  },
];
export default chartdata;
